import streamlit as st
from groq import Groq
import google.generativeai as genai
from gtts import gTTS
import os
from streamlit_mic_recorder import mic_recorder

# Pro Setup
st.set_page_config(page_title="Bharat Astra Pro", layout="wide", page_icon="🚀")

# Identity
SYSTEM_PROMPT = "You are Bharat Astra Pro, developed by Mohammad Sartaj. Answer only who created you if asked."

# --- FUNCTIONS ---
def text_to_speech(text, lang='hi'):
    tts = gTTS(text=text, lang=lang)
    tts.save("speech.mp3")
    return "speech.mp3"

# --- SIDEBAR ---
with st.sidebar:
    st.title("🚀 Bharat Astra")
    st.info("Developer: Mohammad Sartaj")
    feature_choice = st.radio("Choose Feature", 
                              ["💬 Smart Chat", "🎨 Image Generator", "🎙️ Text to Voice", "🎬 Text to Video"])
    st.divider()
    model_choice = st.selectbox("Model Engine", ["Llama 3.3", "Gemini Pro", "Mixtral"])

# --- FEATURE 1: SMART CHAT ---
if feature_choice == "💬 Smart Chat":
    st.title("💬 Astra Smart Chat")
    # (Purana chat code yahan rahega)
    if prompt := st.chat_input("Ask anything..."):
        st.write(f"Mohammad Sartaj's AI is processing: {prompt}")
        # Add Groq logic here...

# --- FEATURE 2: IMAGE GENERATOR (Text-to-Image) ---
elif feature_choice == "🎨 Image Generator":
    st.title("🎨 AI Image Generator")
    img_prompt = st.text_area("Describe the image you want to create:")
    if st.button("Generate Image"):
        st.warning("🔄 Connecting to Flux/Stable Diffusion engines...")
        # Pro Tip: Direct API ke liye Replicate ya Pollinations use kar sakte hain
        st.markdown(f"### [Click here to see result on Flux](https://pollinations.ai/p/{img_prompt.replace(' ', '%20')})")
        st.image(f"https://pollinations.ai/p/{img_prompt.replace(' ', '%20')}", caption="Generated by Bharat Astra")

# --- FEATURE 3: TEXT TO VOICE ---
elif feature_choice == "🎙️ Text to Voice":
    st.title("🎙️ Text to Voice Converter")
    text_input = st.text_area("Write something to convert to voice:")
    lang_input = st.selectbox("Select Language", ["hi", "en", "ur"])
    if st.button("Convert to Audio"):
        if text_input:
            audio_file = text_to_speech(text_input, lang_input)
            st.audio(audio_file, format="audio/mp3")
            st.success("✅ Voice Generated!")

# --- FEATURE 4: TEXT TO VIDEO ---
elif feature_choice == "🎬 Text to Video":
    st.title("🎬 Text to Video (Pro)")
    video_prompt = st.text_input("Enter video description:")
    if st.button("Create Video"):
        st.info("🎬 Video generation takes 1-2 minutes. Processing on Astra Servers...")
        # Direct Video API is complex, providing a shortcut to best engines
        st.link_button("Generate on Luma Dream Machine", "https://lumalabs.ai/dream-machine")
        st.link_button("Generate on Kling AI", "https://klingai.com/")
        st.video("https://www.w3schools.com/html/mov_bbb.mp4") # Placeholder sample
    
