import streamlit as st
from groq import Groq
import google.generativeai as genai
from PIL import Image
import time

# --- BHARAT-ASTRA-GPT ULTRA CONFIG ---
st.set_page_config(page_title="Bharat-Astra-GPT Pro", layout="wide", initial_sidebar_state="collapsed")

# Mohammad Sartaj Identity (Internal logic, no robotic emoji output)
IDENTITY = "You are Bharat-Astra-GPT, a sophisticated AI created by Mohammad Sartaj. Provide high-quality, professional, and accurate responses. Avoid excessive emojis or robotic tone. Focus on deep knowledge."

# --- PREMIUM STYLING (The "Mehanga" Look) ---
st.markdown("""
    <style>
    /* Premium Dark Background */
    .stApp {
        background: radial-gradient(circle at top right, #1e1e26, #111114);
        color: #e3e3e3;
    }
    /* Sleek Chat Input */
    div[data-testid="stChatInputContainer"] {
        padding: 10px !important;
        background-color: #1e1f20 !important;
        border-radius: 32px !important;
        border: 1px solid #3c4043 !important;
        box-shadow: 0 4px 15px rgba(0,0,0,0.5);
    }
    /* Small Circle Loader Styling */
    .stStatus {
        border-radius: 20px;
        background: rgba(255, 255, 255, 0.05);
        border: 0.5px solid #444;
    }
    </style>
    """, unsafe_allow_html=True)

# --- SESSION DATA ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# --- TOP NAV & BRANDING ---
col1, col2 = st.columns([8, 2])
with col1:
    st.title("Bharat-Astra-GPT")
    st.caption("Powered by Mohammad Sartaj's Advanced Neural Engine")

# --- LEFT PLUS (+) MENU (ACTIVE SOUL) ---
with st.sidebar:
    st.markdown("### ➕ Premium Tools")
    st.info("Directly access hardware & storage")
    
    action = st.radio("Select Action", ["💬 Chat Mode", "📸 Live Camera", "🖼️ Media Gallery", "📁 Document Analysis", "🎬 4K Studio"])
    
    if action == "📸 Live Camera":
        st.camera_input("Capture Visuals")
    elif action == "🖼️ Media Gallery":
        st.file_uploader("Select from Gallery", type=['jpg', 'png', 'jpeg'])
    elif action == "📁 Document Analysis":
        st.file_uploader("Upload PDF/Notes", type=['pdf', 'docx'])

# --- CHAT INTERFACE ---
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if "image" in msg:
            st.image(msg["image"])

# --- INPUT & SMART ENGINE ---
if prompt := st.chat_input("Ask Mohammad Sartaj's AI..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        # Gemini-style Small Circle Loader Logic
        status_label = "Creating..." if any(x in prompt.lower() for x in ["image", "photo", "create"]) else "Wait a sec..."
        
        with st.status(status_label, expanded=True) as status:
            time.sleep(1) # Thinking feel
            
            # --- 1. HUMAN-REAL IMAGE GENERATION ---
            if any(x in prompt.lower() for x in ["image", "photo", "human", "face"]):
                st.write("Anatomical structures check...")
                # Pro Tip: Adding quality tags internally for 4K human results
                enhanced_prompt = f"{prompt}, hyper-realistic, 8k, photorealistic, cinematic lighting, perfect anatomy, high skin detail"
                img_url = f"https://pollinations.ai/p/{enhanced_prompt.replace(' ', '%20')}?width=1024&height=1024&model=flux&nologo=true"
                st.image(img_url)
                ans = "Your hyper-realistic visual has been generated by Bharat-Astra-GPT."
                st.session_state.messages.append({"role": "assistant", "content": ans, "image": img_url})
            
            # --- 2. DEEP RESEARCH & TEXT ---
            else:
                st.write("Searching global databases...")
                client = Groq(api_key=st.secrets["GROQ_KEY"])
                response = client.chat.completions.create(
                    model="llama-3.3-70b-versatile",
                    messages=[{"role": "system", "content": IDENTITY}] + st.session_state.messages
                )
                ans = response.choices[0].message.content
                st.markdown(ans)
                st.session_state.messages.append({"role": "assistant", "content": ans})
            
            status.update(label="Analysis Complete", state="complete")

