import streamlit as st
from groq import Groq
import google.generativeai as genai
from fpdf import FPDF
from PIL import Image
import time

# --- BHARAT-ASTRA-GPT CONFIG ---
st.set_page_config(page_title="Bharat-Astra-GPT", layout="wide", page_icon="🚀")

# Identity Setup
IDENTITY = "You are Bharat-Astra-GPT, a world-class AI system developed by Mohammad Sartaj. You are highly intelligent, can perform deep research, and provide expert NCERT solutions."

# Custom CSS for Premium "Dark Glass" Look
st.markdown("""
    <style>
    .stApp { background: linear-gradient(135deg, #0f0c29, #302b63, #24243e); color: white; }
    .stButton>button { border-radius: 20px; border: 1px solid #00d2ff; background: transparent; color: #00d2ff; }
    .stChatInputContainer { border-top: 1px solid #444; }
    </style>
    """, unsafe_allow_html=True)

# --- SIDEBAR (Premium Controls) ---
with st.sidebar:
    st.title("🚀 Bharat-Astra-GPT")
    st.markdown(f"**Dev:** Mohammad Sartaj")
    st.divider()
    model_mode = st.radio("Intelligence Level", ["⚡ Flash (Super Fast)", "🧠 Thinking (Deep Analysis)", "🔍 Research (Live Internet)"])
    st.divider()
    st.success("Premium Member Access")

# --- MAIN INTERFACE ---
st.title("Bharat-Astra-GPT")

# Tabs for Different "Mehangi" Features
tab1, tab2, tab3, tab4 = st.tabs(["💬 Chat", "🎨 4K Studio", "📚 Study/PDF", "🌐 Research"])

# --- TAB 1: ADVANCED CHAT ---
with tab1:
    if "messages" not in st.session_state: st.session_state.messages = []
    
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]): st.markdown(msg["content"])

    if prompt := st.chat_input("Ask Bharat-Astra-GPT anything..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"): st.markdown(prompt)

        with st.chat_message("assistant"):
            with st.status("🤔 Bharat-Astra-GPT is thinking...", expanded=True) as s:
                # Logic to handle developer identity
                client = Groq(api_key=st.secrets["GROQ_KEY"])
                response = client.chat.completions.create(
                    model="llama-3.3-70b-versatile",
                    messages=[{"role": "system", "content": IDENTITY}] + st.session_state.messages
                )
                answer = response.choices[0].message.content
                s.update(label="✅ Analysis Complete", state="complete")
            st.markdown(answer)
            st.session_state.messages.append({"role": "assistant", "content": answer})

# --- TAB 2: 4K IMAGE STUDIO ---
with tab2:
    st.subheader("🎨 Premium 4K Image Generation")
    img_desc = st.text_input("Enter prompt for 4K Image:")
    if st.button("Generate Masterpiece"):
        # High quality parameters
        url = f"https://pollinations.ai/p/{img_desc.replace(' ', '%20')}?width=3840&height=2160&model=flux&seed=99"
        st.image(url, caption="Generated by Bharat-Astra-GPT 4K Engine")

# --- TAB 3: STUDY & PDF BRAIN ---
with tab3:
    st.subheader("📚 NCERT & PDF Intelligence")
    uploaded_pdf = st.file_uploader("Upload Book/PDF for Analysis", type="pdf")
    if uploaded_pdf:
        st.success("PDF Loaded! Bharat-Astra-GPT is reading it...")
    
    study_topic = st.text_input("Topic for NCERT Notes:")
    if st.button("Create Pro Notes"):
        genai.configure(api_key=st.secrets["GEMINI_KEY"])
        model = genai.GenerativeModel('gemini-1.5-pro')
        res = model.generate_content(f"{IDENTITY} Create detailed NCERT notes for: {study_topic}")
        st.markdown(res.text)

# --- TAB 4: LIVE RESEARCH ---
with tab4:
    st.subheader("🌐 Real-time Web Research")
    research_query = st.text_input("What do you want to research live?")
    if st.button("Start Deep Research"):
        with st.spinner("Searching global databases..."):
            # Using Gemini Pro for high-level reasoning
            genai.configure(api_key=st.secrets["GEMINI_KEY"])
            model = genai.GenerativeModel('gemini-1.5-pro')
            res = model.generate_content(f"Research and provide a detailed report with facts on: {research_query}")
            st.info("Source: Bharat-Astra-GPT Live Research Module")
            st.write(res.text)

# --- BOTTOM FLOATING BUTTONS (As per your Screenshot) ---
st.divider()
footer_cols = st.columns(4)
footer_cols[0].button("📷 Camera")
footer_cols[1].button("📂 Gallery")
footer_cols[2].button("📎 Files")
footer_cols[3].button("☁️ Drive")
